default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: vuash_development

test:
  <<: *default
  database: vuash_test

test: &test
  <<: *default
  database: vuash_test

cucumber:
  <<: *test
